### ISSUE TITLE
Really invasive error message

### ISSUE THREAD

**Issue by ferdi2005** [valerio-bozzolan/suckless-wp-net-smtp#1]
My sysadmin installed me this plugin and assured me that he put the requested credentials into wp-settings.php. It wasn't true but this isn't the point. 
This plugin literally **blocked** the entire site admin area just to remember me that I didn't put the credentials. It can be of 133 lines of code, but maybe plugins with more lines of code don't block your entire site just because you forgot to put credentials and just show you a fancy notice...
I think this should be fixed.

**Comment by ferdi2005** [comment]
But it's a fantastic plugin for the other things, there's only this little problem to fix. @valerio-bozzolan

**Comment by valerio-bozzolan** [comment]
asd
